#!/usr/bin/env python3
"""
Build the vocabulary HTML from unit files.

  units/TextN.json           -> word data (word, pos, phonetic, definition, note, example)
  images/TextN/NN_word.png   -> one illustration per word (generated by the agent)

Requires: Pillow (pip install Pillow)

Project: 007_米米背单词
Usage:   python3 build.py          (run from anywhere; paths resolve relative to this file)
Outputs: <project>/背单词-学习卡片.html   (single file, images embedded, works offline)
         <project>/index.html            (same file, ready for web publishing)
"""
import base64, glob, io, json, os, sys
from PIL import Image

# paths resolve from the script's own location, so the project folder can be moved anywhere
ROOT = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(ROOT)
UNITS_DIR = os.path.join(ROOT, "units")
IMG_DIR = os.path.join(ROOT, "images")
TPL = os.path.join(ROOT, "template.html")
OUT = os.path.join(PROJECT, "背单词-学习卡片.html")
INDEX = os.path.join(PROJECT, "index.html")
SITE = os.path.join(PROJECT, "site", "index.html")  # clean copy for web publishing (no source images)
SIZE, QUALITY = (720, 480), 70


def slugify(word):
    return word.replace("-", "_").replace(" ", "_").replace("/", "_").lower()


def unit_sort_key(path):
    """Text2 < Text10 (natural number order)."""
    name = os.path.basename(path)
    m = [c for c in name if c.isdigit()]
    return (int("".join(m)) if m else 0, name)


def main():
    files = sorted(glob.glob(os.path.join(UNITS_DIR, "*.json")), key=unit_sort_key)
    if not files:
        sys.exit("no unit files found in " + UNITS_DIR)

    units = []
    for fp in files:
        u = json.load(open(fp, encoding="utf-8"))
        uid, idir = u["id"], os.path.join(IMG_DIR, u["id"])
        missing = []
        for i, w in enumerate(u["words"], 1):
            slug = slugify(w["w"])
            cands = sorted(glob.glob(os.path.join(idir, "*_%s.png" % slug)))
            if not cands:
                missing.append(w["w"])
                w["img"] = ""
                continue
            im = Image.open(cands[0]).convert("RGB").resize(SIZE, Image.LANCZOS)
            buf = io.BytesIO()
            im.save(buf, "JPEG", quality=QUALITY, optimize=True, progressive=True)
            small_dir = os.path.join(idir, "small")
            os.makedirs(small_dir, exist_ok=True)
            open(os.path.join(small_dir, "%02d_%s.jpg" % (i, slug)), "wb").write(buf.getvalue())
            w["img"] = "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()
        units.append(u)
        print("  %-6s %2d words  %s" % (uid, len(u["words"]),
              ("missing images: " + ", ".join(missing)) if missing else "images ok"))

    tpl = open(TPL, encoding="utf-8").read()
    ph = "/*__UNITDATA__*/ []"
    if ph not in tpl:
        sys.exit("template placeholder not found: " + ph)
    html = tpl.replace(ph, json.dumps(units, ensure_ascii=False))
    open(OUT, "w", encoding="utf-8").write(html)
    open(INDEX, "w", encoding="utf-8").write(html)  # copy at project root
    os.makedirs(os.path.dirname(SITE), exist_ok=True)
    open(SITE, "w", encoding="utf-8").write(html)   # copy for publishing

    print("built -> %s  (%.2f MB, %d units, %d words)" % (
        OUT, os.path.getsize(OUT) / 1024 / 1024, len(units),
        sum(len(u["words"]) for u in units)))
    print("         " + INDEX)
    print("         " + SITE + "   <- publish this folder")


if __name__ == "__main__":
    main()
